### ISSUE TITLE
Not finding git version with out-of-tree build

### ISSUE THREAD

**Issue by vanrein** [arpa2/arpa2cm#2]
When trying to establish the version from Git, the ARPA2CM module:
 - produces the right version in a subtree from the source (like ./build)
 - claims not to be in a Git repository during builds outside the source tree (like /tmp/build)

To reproduce (output shown below):
 * pull in the repository: `git clone https://github.com/vanrein/perpetuum`
 * change into the directory and branch: `cd perpetuum ; git checkout arpa2cm`
 * Properly tag a version: `git tag version-0.9-0 version-0.9.0`
 * run cmake in a subdirectory of the source like ./build: `mkdir build ; cd build ; cmake ..`
 * run cmake in another directory like /tmp/build: `mkdir /tmp/build ; cd /tmp/build ; cmake /path/to/perpetuum`

Surprisingly, the added commands in the project's CMakeLists.txt do seem to work in both cases, and recover the git tag.  This is all the more astounding because the Git version retriever does change to ${CMAKE_CURRENT_SOURCE_DIR} first.

The first test produces:
```
-- Looking for git-versioning information.
running /usr/local/bin/git diff --quiet  2>&1
  Got version 0.9.0-8-gbcb63c1
-- Found program version 0.9.0-8-gbcb63c1
-- Git is /usr/local/bin/git
-- Git was tested: version-0.9-0-8-gbcb63c1
```

The second test produces:
```
-- Looking for git-versioning information.
running /usr/local/bin/git diff --quiet  2>&1
Not a git repository
To compare two paths outside a working tree:
usage: git diff [--no-index] <path> <path>
  Git reports local changes, fixing patch level to local-20180203-164603
  Got version fatal: Not a git repository (or any of the parent directories): .git.fatal: Not a git repository (or any of the parent directories): .git.local-20180203-164603
-- Found program version fatal: Not a git repository (or any of the parent directories): .git.fatal: Not a git repository (or any of the parent directories): .git.local-20180203-164603
-- Git is /usr/local/bin/git
-- Git was tested: version-0.9-0-8-gbcb63c1
```

I am stymned... without a clue of what could be wrong.  Help?

**Comment by vanrein** [comment]
I tried setting `--git-dir` and `--work-tree` and neither solved the problem.

FWIW, git operates fine in the source directory...

**Comment by vanrein** [comment]
Same with `-C ${CMAKE_CURRENT_SOURCE_DIR}`.

I also tried combinations with `${CMAKE_SOURCE_DIR}` which is more accurate, at least for `git diff`, although I cannot think of a situation where the difference would be noticeable.

Anyway, none of the 2x3 combinations showed a difference.

**Comment by vanrein** [comment]
My hunch is correct; git is running in the current directory, which explains why builds work inside the source tree but not outside.

Before running CMake in /tmp/perpetuum, I ran `git init` in /tmp and got
```
-- Looking for git-versioning information.
running /usr/local/bin/git diff --quiet  2>&1
  Got version fatal: No names found, cannot describe anything..fatal: No names found, cannot describe anything..fatal: No names found, cannot describe anything.
-- Found program version fatal: No names found, cannot describe anything..fatal: No names found, cannot describe anything..fatal: No names found, cannot describe anything.
-- Git is /usr/local/bin/git
-- Git was tested: version-0.9-0-8-gbcb63c1
```

Yes, no tags were made.  So from /tmp/perpetuum I did
```
touch ../x
git add ../x
git commit -m Blissfully_Empty
git tag version-6.6-6
```

The result after this was clearly wrong not what is intended:
```
-- Looking for git-versioning information.
running /usr/local/bin/git diff --quiet  2>&1
  Got version 6.6.6
-- Found program version 6.6.6
-- Git is /usr/local/bin/git
-- Git was tested: version-0.9-0-8-gbcb63c1
```

There would seem to be something forcing Git to look at the `${CMAKE_BINARY_DIR}` instead of the `${CMAKE_SOURCE_DIR}`, but I have no idea what it is.  There are no environment variables to Git, as far as I can tell.

The error I got with `.git.fatal` indicated the absense of a Git repo, which make sense in this light.

**Comment by adriaandegroot** [comment]
> The first test produces:
> ```
> -- Looking for git-versioning information.
> running /usr/local/bin/git diff --quiet  2>&1
> ```

That, at least, is wrong. It may be because of your CMake version or platform, or because you're doing something weird with current source dir anyway. In my experiments **not** with perpetuum, the output looks like this:

```
-- Looking for git-versioning information.                                                   
running cd "/home/adridg/src/tmp" && /usr/bin/git diff --quiet  2>&1         
```

Notice the extra `cd` in the command.

**Comment by adriaandegroot** [comment]
> Properly tag a version: git tag version-0.9-0 version-0.9.0

That's not a proper tag according to the git-versioning module. It must be *version-0.9-0* (with a dash).

**Comment by adriaandegroot** [comment]
Perpetuum pretends to use ARPA2CM, but it has a `cmake/` subdirectory that still contains old versions of, e.g., `MacroGitVersionInfo.cmake`. It uses those, and they **don't** have any of the fixes ever applied to ARPA2CM. Please remove them, remove the cmake/ directory if it is no longer needed (I don't think it is, everything looks boilerplate), remove setting of `CMAKE_MODULE_PATH`, and after finding ARPA2CM, add

```
set (CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} 
    ${ARPA2CM_MODULE_PATH})
```

**Comment by vanrein** [comment]
*BLUSH*

Thanks, Ade!
